# Generated by Django 3.2.15 on 2024-02-29 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=50, verbose_name='адрес')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Долгота')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата запроса')),
            ],
            options={
                'unique_together': {('address', 'lat', 'lon')},
            },
        ),
    ]
