# Generated by Django 3.2.15 on 2024-02-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20240226_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'Обработанный'), ('UN', 'Необработанный')], default='UN', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
