# Generated by Django 3.2.15 on 2024-02-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20240226_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('CARD', 'Электронно')], default='CASH', max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
