# Generated by Django 3.2.15 on 2024-03-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20240229_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличными'), ('CARD', 'Электронно'), ('NS', 'Не указано')], default='NS', max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
